### PR TITLE
Checkout a working pc-gadget commit, use stable EdgeX snaps

### LINKED ISSUE #1: Installation error on latest core22 pc-gadget
The UC installation fails with the following log:
```
[  OK  ] Started /run/mnt/snapd/usr/lib/snapd/snapd.
[    8.800399] systemd[1]: Started /run/mnt/snapd/usr/lib/snapd/snapd.
[    8.801206] snapd[892]: firstboot.go:401: failed to auto-import assertions: open /var/lib/snapd/seed/systems/20230517/auto-import.assert: no such file or directory
[   10.031860] systemd-timesyncd[844]: Network configuration changed, trying to establish connection.
[   10.038923] snapd[892]: stateengine.go:149: state ensure error: devicemgr: cannot seed: snap "pc" assumes unsupported features: snapd2.59.3 (try to refresh snapd)
[   12.975541] systemd[1]: Created slice Slice /system/console-conf.
[   40.336100] systemd-resolved[854]: Clock change detected. Flushing caches.
[   40.336606] systemd-timesyncd[844]: Initial synchronization to time server 185.125.190.58:123 (ntp.ubuntu.com).
[   98.020608] systemd[1]: getty@tty1.service: start-pre operation timed out. Terminating.
[   98.021060] systemd[1]: getty@tty1.service: Control process exited, code=killed, status=15/TERM
[   98.021140] systemd[1]: getty@tty1.service: Failed with result 'timeout'.
[   98.022444] systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 1.
[   98.022531] systemd[1]: Stopped Getty on tty1.
[   98.023267] systemd[1]: Started Getty on tty1.
[  188.270217] systemd[1]: getty@tty1.service: start-pre operation timed out. Terminating.
[  188.270633] systemd[1]: getty@tty1.service: Control process exited, code=killed, status=15/TERM
[  188.270736] systemd[1]: getty@tty1.service: Failed with result 'timeout'.
[  188.272781] systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 2.
[  188.273082] systemd[1]: Stopped Getty on tty1.
[  188.274056] systemd[1]: Started Getty on tty1.
```

To make the UC image build work work, one should checkout commit [`1779b0de4e022ddcbefd782e0523ee9c0c7f1dea`](https://github.com/snapcore/pc-gadget/commit/1779b0de4e022ddcbefd782e0523ee9c0c7f1dea) for the pc-gadget.

_Originally posted by @farshidtz in https://github.com/canonical/edgex-snap-testing/pull/205#pullrequestreview-1434542853_

### LINKED ISSUE #2: Input USER variable is always set
https://github.com/canonical/edgex-ubuntu-core-testing/blob/8f8e7187732a0293050e7c384b625d3ce58381af/test.sh#L3

This variable is always set in bash. Need to change to something different.

### PR DESCRIPTION
**Pull request by MonicaisHer**
use non-system reserved variable name

This PR
- resolves #1
- resolves #2

### CODE REVIEW

**Comment by farshidtz** [comment]
Config Provider has just be released on latest/stable.

File: build-gadget.sh [hunk 1]
```diff
@@ -2,11 +2,14 @@
 
 # Remove the pc-gadget directory if it already exists
 rm -rf pc-gadget
-git clone https://github.com/snapcore/pc-gadget.git --branch=22 --depth 1 
 
-# Build gadget snap
+git clone https://github.com/snapcore/pc-gadget.git
```
Comment (farshidtz) [inline build-gadget.sh]: Why is the branch removed? It is still useful to make it clear that this is based on the core22 gadget:
```suggestion
git clone https://github.com/snapcore/pc-gadget.git --branch=22
```

**Review by farshidtz — CHANGES_REQUESTED** [review]

File: build-gadget.sh (hunk 1 above)
Comment (MonicaisHer) [reply build-gadget.sh]: Because they explicitly check out the same commit, the end result would be the same. 

But I understand your point. I will apply your suggestion, thanks.

**Review by farshidtz — APPROVED** [review]
Looks good. Keeping in mind that 2.59.4 snapd has recently been promoted to latest/stable, so the compatibility issue no longer exists. It is nevertheless a good idea to test based on a commit known to be working.

I updated the PR description to resolve both issues on merge, not just one.
